import "./globals.css";
import BottomNavbar from "./components/BottomNavbar";
import GlobalNavbar from "./components/Navbar";

export const metadata = {
  title: "MegaMiner BDT",
  description: "Virtual Mining Platform",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-950 text-white min-h-screen pb-20 md:pb-0">
        <GlobalNavbar />
        {/* মূল পেজের কন্টেন্ট */}
        <main>{children}</main>

        {/* মোবাইল বটম নেভিগেশন বার */}
        <BottomNavbar />
      </body>
    </html>
  );
}

// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
